- name: Configure Django
  hosts: prod 
  tasks:
    - name: install git 
      apt: name=git update_cache=yes

#    - name: install virtualenv 
#      apt: name=virtualenv update_cache=yes

#    - name: Manually create virtualenv
#      command: virtualenv /home/nandersson/venvs2/freemarketmalaga creates="/home/nandersson/venvs2/freemarketmalaga"

    - name: install virtualenv 
      apt: name=python3-venv update_cache=yes

    - name: install pip3 
      apt: name=python3-pip update_cache=yes

    - name: Manually create virtualenv
      command: python3 -m venv /home/nandersson/venvs3/freemarketmalaga creates="/home/nandersson/venvs3/freemarketmalaga"

    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/default.freemarketmalaga dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: git checkout
      git: repo='https://github.com/xnandersson/free-market-malaga.git' dest=/var/www/free-market-malaga

    - name: copy local_settings.py
      copy: src=files/local_settings.py dest=/var/www/free-market-malaga/src/freemarketmalaga/

    - name: Install Requirements
      pip: 
        requirements: "/var/www/free-market-malaga/requirements.txt"
        virtualenv: "/home/nandersson/venvs3/freemarketmalaga"
        virtualenv_python: python3
        executable: pip3

    - name: Django Migrate
      django_manage:
        command: migrate
        app_path: "/var/www/free-market-malaga/src"
        virtualenv: "/home/nandersson/venvs3/freemarketmalaga"

    - name: Django Collect Static
      django_manage:
        command: collectstatic
        app_path: "/var/www/free-market-malaga/src"
        virtualenv: "/home/nandersson/venvs3/freemarketmalaga"

#    - name: Django SuperUser
#      django_manage:
#        command: "createsuperuser --noinput --username=nandersson --email=n@n.com" 
#        app_path: "/var/www/free-market-malaga/src"
#        virtualenv: "/home/nandersson/venvs2/freemarketmalaga"

#    - name: Gunicorn
#      gunicorn: app = 'wsgi' chdir = '/var/www/free-market-malaga/src/' venv = '/home/nandersson/venvs2/freemarketmalaga'

    - name: FreeMarketMalaga Service
      copy: src=files/freemarketmalaga.service dest=/etc/systemd/system/freemarketmalaga.service

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart gunicorn
      service: name=freemarketmalaga state=restarted
