- name: Configure postgres 
  hosts: dev 
  tasks:
    - name: install python-psycopg2
      apt: name=python-psycopg2 state=installed update_cache=yes

    - name: install postgresql
      apt: name={{item}} state=installed update_cache=yes
      with_items:
        - libpq-dev
        - postgresql
        - postgresql-contrib

    - name: start postgresql
      service: name=postgresql state=restarted

    - name: Create Postgresql Superuser
      become: True
      become_user: postgres
      postgresql_user:
        name: blackbird 
        password: Secret007
        encrypted: True
        role_attr_flags: SUPERUSER

    - name: Create Django Postgresql user
      become: True
      become_user: postgres
      postgresql_user:
        name: django
        password: Secret11
        encrypted: True
        role_attr_flags: LOGIN,NOSUPERUSER,NOCREATEDB

    - name: create database
      become_user: postgres
      postgresql_db:
        login_user: blackbird
        login_password: Secret007
        login_host: 127.0.0.1
        port: 5432
        name: freemarketmalaga
        owner: django
        encoding: UTF-8
        template: template0
