- name: Configure webserver with nginx
  hosts: dev 
  sudo: True
  tasks:
    - name: install git 
      apt: name=git update_cache=yes

    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/default dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: git checkout
      git: repo='https://github.com/xnandersson/free-market-malaga.git' dest=/var/www/free-market-malaga

    - name: restart nginx
      service: name=nginx state=restarted
