- name: Configure webserver with nginx
  hosts: dev 
  tasks:
    - name: install git 
      apt: name=git update_cache=yes

    - name: install python-psycopg2
      apt: name=python-psycopg2 state=installed

    - name: install postgresql
      apt: name={{item}} state=installed
      with_items:
        - libpq-dev
        - postgresql
        - postgresql-contrib

    - name: start postgresql
      service: name=postgresql state=restarted

    - name: Create Postgresql Superuser
      become: True
      become_user: postgres
      postgresql_user:
        name: blackbird 
        password: Secret007
        encrypted: True
        role_attr_flags: SUPERUSER

    - name: Create Django Postgresql user
      become: True
      become_user: postgres
      postgresql_user:
        name: django
        password: Secret11
        encrypted: True
        role_attr_flags: LOGIN,NOSUPERUSER,NOCREATEDB

    - name: create database
      become_user: postgres
      postgresql_db:
        login_user: blackbird
        login_password: Secret007
        login_host: 127.0.0.1
        port: 5432
        name: freemarketmalaga
        owner: django
        encoding: UTF-8
        template: template0

    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/default.freemarketmalaga dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: git checkout
      git: repo='https://github.com/xnandersson/free-market-malaga.git' dest=/var/www/free-market-malaga

    - name: restart nginx
      service: name=nginx state=restarted
