- name: Configure webserver with nginx
  hosts: dev 
  become: yes
  become_method: sudo
  tasks:
    - name: install git 
      apt: name=git update_cache=yes

    - name: install python3
      apt: name={{item}} state=installed
      with_items:
        - python3-pip
        - python3-dev
        - python3-psycopg2

    - name: install postgresql
      apt: name={{item}} state=installed
      with_items:
        - libpq-dev
        - postgresql
        - postgresql-contrib

    - name: install nginx
      apt: name=nginx update_cache=yes

    - name: copy nginx config file
      copy: src=files/default dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: git checkout
      git: repo='https://github.com/xnandersson/free-market-malaga.git' dest=/var/www/free-market-malaga

    - name: restart nginx
      service: name=nginx state=restarted
